// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: pkg/api/grpc_service/service.proto

package grpc_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SetWaists
type SetWaistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Waists        []*Waist               `protobuf:"bytes,1,rep,name=waists,proto3" json:"waists,omitempty"`
	DateCreated   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=date_created,json=dateCreated,proto3" json:"date_created,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetWaistsRequest) Reset() {
	*x = SetWaistsRequest{}
	mi := &file_pkg_api_grpc_service_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetWaistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetWaistsRequest) ProtoMessage() {}

func (x *SetWaistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_grpc_service_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetWaistsRequest.ProtoReflect.Descriptor instead.
func (*SetWaistsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_grpc_service_service_proto_rawDescGZIP(), []int{0}
}

func (x *SetWaistsRequest) GetWaists() []*Waist {
	if x != nil {
		return x.Waists
	}
	return nil
}

func (x *SetWaistsRequest) GetDateCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.DateCreated
	}
	return nil
}

func (x *SetWaistsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type Waist struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupName     string                 `protobuf:"bytes,1,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	Value         int64                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Waist) Reset() {
	*x = Waist{}
	mi := &file_pkg_api_grpc_service_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Waist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Waist) ProtoMessage() {}

func (x *Waist) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_grpc_service_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Waist.ProtoReflect.Descriptor instead.
func (*Waist) Descriptor() ([]byte, []int) {
	return file_pkg_api_grpc_service_service_proto_rawDescGZIP(), []int{1}
}

func (x *Waist) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *Waist) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// GetLastWaists
type GetLastWaistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        int64                  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLastWaistsRequest) Reset() {
	*x = GetLastWaistsRequest{}
	mi := &file_pkg_api_grpc_service_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastWaistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastWaistsRequest) ProtoMessage() {}

func (x *GetLastWaistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_grpc_service_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastWaistsRequest.ProtoReflect.Descriptor instead.
func (*GetLastWaistsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_grpc_service_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetLastWaistsRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *GetLastWaistsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetLastWaistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Waists        []*Waists              `protobuf:"bytes,1,rep,name=waists,proto3" json:"waists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLastWaistsResponse) Reset() {
	*x = GetLastWaistsResponse{}
	mi := &file_pkg_api_grpc_service_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastWaistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastWaistsResponse) ProtoMessage() {}

func (x *GetLastWaistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_grpc_service_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastWaistsResponse.ProtoReflect.Descriptor instead.
func (*GetLastWaistsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_grpc_service_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetLastWaistsResponse) GetWaists() []*Waists {
	if x != nil {
		return x.Waists
	}
	return nil
}

type Waists struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Waists        []*Waist               `protobuf:"bytes,1,rep,name=waists,proto3" json:"waists,omitempty"`
	DateCreated   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=DateCreated,proto3" json:"DateCreated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Waists) Reset() {
	*x = Waists{}
	mi := &file_pkg_api_grpc_service_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Waists) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Waists) ProtoMessage() {}

func (x *Waists) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_grpc_service_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Waists.ProtoReflect.Descriptor instead.
func (*Waists) Descriptor() ([]byte, []int) {
	return file_pkg_api_grpc_service_service_proto_rawDescGZIP(), []int{4}
}

func (x *Waists) GetWaists() []*Waist {
	if x != nil {
		return x.Waists
	}
	return nil
}

func (x *Waists) GetDateCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.DateCreated
	}
	return nil
}

// CreateUser
type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_pkg_api_grpc_service_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_grpc_service_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_grpc_service_service_proto_rawDescGZIP(), []int{5}
}

func (x *CreateUserRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Login         string                 `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_pkg_api_grpc_service_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_grpc_service_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_grpc_service_service_proto_rawDescGZIP(), []int{6}
}

func (x *CreateUserResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateUserResponse) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

// GetUser
type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_pkg_api_grpc_service_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_grpc_service_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_grpc_service_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Login         string                 `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_pkg_api_grpc_service_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_grpc_service_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_grpc_service_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetUserResponse) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *GetUserResponse) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

var File_pkg_api_grpc_service_service_proto protoreflect.FileDescriptor

const file_pkg_api_grpc_service_service_proto_rawDesc = "" +
	"\n" +
	"\"pkg/api/grpc_service/service.proto\x12\fgrpc_service\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x97\x01\n" +
	"\x10SetWaistsRequest\x12+\n" +
	"\x06waists\x18\x01 \x03(\v2\x13.grpc_service.WaistR\x06waists\x12=\n" +
	"\fdate_created\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vdateCreated\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\"<\n" +
	"\x05Waist\x12\x1d\n" +
	"\n" +
	"group_name\x18\x01 \x01(\tR\tgroupName\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value\"G\n" +
	"\x14GetLastWaistsRequest\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x03R\x06amount\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"E\n" +
	"\x15GetLastWaistsResponse\x12,\n" +
	"\x06waists\x18\x01 \x03(\v2\x14.grpc_service.WaistsR\x06waists\"s\n" +
	"\x06Waists\x12+\n" +
	"\x06waists\x18\x01 \x03(\v2\x13.grpc_service.WaistR\x06waists\x12<\n" +
	"\vDateCreated\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vDateCreated\"E\n" +
	"\x11CreateUserRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\":\n" +
	"\x12CreateUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05login\x18\x02 \x01(\tR\x05login\"&\n" +
	"\x0eGetUserRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\"S\n" +
	"\x0fGetUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05login\x18\x02 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword2\xc6\x02\n" +
	"\fWaistService\x12C\n" +
	"\tSetWaists\x12\x1e.grpc_service.SetWaistsRequest\x1a\x16.google.protobuf.Empty\x12X\n" +
	"\rGetLastWaists\x12\".grpc_service.GetLastWaistsRequest\x1a#.grpc_service.GetLastWaistsResponse\x12O\n" +
	"\n" +
	"CreateUser\x12\x1f.grpc_service.CreateUserRequest\x1a .grpc_service.CreateUserResponse\x12F\n" +
	"\aGetUser\x12\x1c.grpc_service.GetUserRequest\x1a\x1d.grpc_service.GetUserResponseB\x1aZ\x18app/pkg/api/grpc_serviceb\x06proto3"

var (
	file_pkg_api_grpc_service_service_proto_rawDescOnce sync.Once
	file_pkg_api_grpc_service_service_proto_rawDescData []byte
)

func file_pkg_api_grpc_service_service_proto_rawDescGZIP() []byte {
	file_pkg_api_grpc_service_service_proto_rawDescOnce.Do(func() {
		file_pkg_api_grpc_service_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_grpc_service_service_proto_rawDesc), len(file_pkg_api_grpc_service_service_proto_rawDesc)))
	})
	return file_pkg_api_grpc_service_service_proto_rawDescData
}

var file_pkg_api_grpc_service_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pkg_api_grpc_service_service_proto_goTypes = []any{
	(*SetWaistsRequest)(nil),      // 0: grpc_service.SetWaistsRequest
	(*Waist)(nil),                 // 1: grpc_service.Waist
	(*GetLastWaistsRequest)(nil),  // 2: grpc_service.GetLastWaistsRequest
	(*GetLastWaistsResponse)(nil), // 3: grpc_service.GetLastWaistsResponse
	(*Waists)(nil),                // 4: grpc_service.Waists
	(*CreateUserRequest)(nil),     // 5: grpc_service.CreateUserRequest
	(*CreateUserResponse)(nil),    // 6: grpc_service.CreateUserResponse
	(*GetUserRequest)(nil),        // 7: grpc_service.GetUserRequest
	(*GetUserResponse)(nil),       // 8: grpc_service.GetUserResponse
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 10: google.protobuf.Empty
}
var file_pkg_api_grpc_service_service_proto_depIdxs = []int32{
	1,  // 0: grpc_service.SetWaistsRequest.waists:type_name -> grpc_service.Waist
	9,  // 1: grpc_service.SetWaistsRequest.date_created:type_name -> google.protobuf.Timestamp
	4,  // 2: grpc_service.GetLastWaistsResponse.waists:type_name -> grpc_service.Waists
	1,  // 3: grpc_service.Waists.waists:type_name -> grpc_service.Waist
	9,  // 4: grpc_service.Waists.DateCreated:type_name -> google.protobuf.Timestamp
	0,  // 5: grpc_service.WaistService.SetWaists:input_type -> grpc_service.SetWaistsRequest
	2,  // 6: grpc_service.WaistService.GetLastWaists:input_type -> grpc_service.GetLastWaistsRequest
	5,  // 7: grpc_service.WaistService.CreateUser:input_type -> grpc_service.CreateUserRequest
	7,  // 8: grpc_service.WaistService.GetUser:input_type -> grpc_service.GetUserRequest
	10, // 9: grpc_service.WaistService.SetWaists:output_type -> google.protobuf.Empty
	3,  // 10: grpc_service.WaistService.GetLastWaists:output_type -> grpc_service.GetLastWaistsResponse
	6,  // 11: grpc_service.WaistService.CreateUser:output_type -> grpc_service.CreateUserResponse
	8,  // 12: grpc_service.WaistService.GetUser:output_type -> grpc_service.GetUserResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_api_grpc_service_service_proto_init() }
func file_pkg_api_grpc_service_service_proto_init() {
	if File_pkg_api_grpc_service_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_grpc_service_service_proto_rawDesc), len(file_pkg_api_grpc_service_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_grpc_service_service_proto_goTypes,
		DependencyIndexes: file_pkg_api_grpc_service_service_proto_depIdxs,
		MessageInfos:      file_pkg_api_grpc_service_service_proto_msgTypes,
	}.Build()
	File_pkg_api_grpc_service_service_proto = out.File
	file_pkg_api_grpc_service_service_proto_goTypes = nil
	file_pkg_api_grpc_service_service_proto_depIdxs = nil
}
